api:
  - "config/docker/api.Dockerfile"
  - "config/flatbuffers/**"
  - "api/**"

app:
  - "config/docker/app.Dockerfile"
  - "app/**"

cmp:
  - "config/docker/cmp.Dockerfile"
  - "cmp/**"

ops:
  - "devops/**"

docs:
  - "docs/**"

links:
  - "**/*.md"

sdk_cpp:
  - "sdk/cpp/**"

sdk_java:
  - "sdk/java/**"

sdk_js:
  - "sdk/js/**"

sdk_python:
  - "sdk/python/**"

examples_cpp:
  - "examples/cpp/**"
  - "sdk/cpp/**"

examples_java:
  - "examples/java/**"

examples_js:
  - "examples/js/**"

examples_python:
  - "examples/python/**"

web:
  - "web/**"
