api:
  - ".github/workflows/build.yml"
  - "api/**"
  - "config/docker/**"
  - "config/flatbuffers/**"
  - "packages/api-schema/**"
  - "packages/comparator/**"
  - "packages/flatbuffers/**"

app:
  - ".github/workflows/build.yml"
  - "app/**"

ops:
  - ".github/workflows/build.yml"
  - "ops/**"

docs:
  - ".github/workflows/build.yml"
  - "docs/**"

links:
  - "**/*.md"

sdk_cpp:
  - ".github/workflows/build.yml"
  - "sdk/cpp/**"

sdk_java:
  - ".github/workflows/build.yml"
  - "sdk/java/**"

sdk_js:
  - ".github/workflows/build.yml"
  - "sdk/js/**"

sdk_python:
  - ".github/workflows/build.yml"
  - "sdk/python/**"

examples_cpp:
  - ".github/workflows/build.yml"
  - "examples/cpp/**"
  - "sdk/cpp/**"

examples_java:
  - ".github/workflows/build.yml"
  - "examples/java/**"

examples_js:
  - ".github/workflows/build.yml"
  - "examples/js/**"

examples_python:
  - ".github/workflows/build.yml"
  - "examples/python/**"

web:
  - ".github/workflows/build.yml"
  - "web/**"
