docs:
  - ".github/workflows/build.yml"
  - "docs/**"

links:
  - "**/*.md"

examples_cpp:
  - ".github/workflows/build.yml"
  - "examples/cpp/**"

examples_java:
  - ".github/workflows/build.yml"
  - "examples/java/**"

examples_js:
  - ".github/workflows/build.yml"
  - "examples/js/**"

examples_python:
  - ".github/workflows/build.yml"
  - "examples/python/**"

web:
  - ".github/workflows/build.yml"
  - "web/**"
