## Reference: https://github.com/helm/chart-testing/blob/master/doc/ct_lint-and-install.md
# Don't add the 'debug' attribute, otherwise the workflow won't work anymore
# Only Used for the CT Lint Stage
remote: origin
chart-dirs:
  - ops/k8s
chart-repos:
  - touca=https://trytouca.github.io/trytouca
helm-extra-args: "--timeout 600s"  
validate-chart-schema: false
validate-maintainers: true
validate-yaml: true
exclude-deprecated: true
target-branch: main
excluded-charts: []
