/*
 *
 */
package io.touca;

/**
 * This java source file was generated by the Gradle 'init' task.
 */
public class Library {

    /**
     * This java source file was generated by the Gradle 'init' task.
     * 
     * @return true always
     */
    public boolean someLibraryMethod() {
        return true;
    }
}
