apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-touca-minio
  name: {{ .Release.Name }}-touca-minio
  namespace: {{ .Release.Name }}-touca
spec:
  ports:
  - port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: {{ .Release.Name }}-touca-minio