// Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

#pragma once

#define TOUCA_VERSION_MAJOR 1
#define TOUCA_VERSION_MINOR 2
#define TOUCA_VERSION_PATCH 1

#define TOUCA_VERSION (TOUCA_VERSION_MAJOR * 10000 + TOUCA_VERSION_MINOR * 100 + TOUCA_VERSION_PATCH)
