# Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

name: touca-js-main

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - ".github/workflows/javascript.yml"
      - "js/**"

jobs:
  test-native:
    name: unittest-native
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/js/node_modules
            ${{ github.workspace }}/js/packages/**/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - run: yarn --cwd=js install
      - run: yarn --cwd=js build
