apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-touca-app
  name: {{ .Release.Name }}-touca-app
  namespace: {{ .Release.Name }}-touca
spec:
  type: {{ if not .Values.ingress.enabled }}NodePort{{ end }}
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
{{- include "svcIngress" . | indent 4 }}
  selector:
    app: {{ .Release.Name }}-touca-app
