/**
 * Copyright 2018-2020 Pejman Ghorbanzade. All rights reserved.
 */

#pragma once

#define WEASEL_VERSION_MAJOR 1
#define WEASEL_VERSION_MINOR 2
#define WEASEL_VERSION_PATCH 1

#define WEASEL_VERSION (WEASEL_VERSION_MAJOR * 10000 + WEASEL_VERSION_MINOR * 100 + WEASEL_VERSION_PATCH)
