apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-touca-api
  name: {{ .Release.Name }}-touca-api
  namespace: {{ .Release.Name }}-touca
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: {{ .Release.Name }}-touca-api
