# Copyright 2022 Touca, Inc. Subject to Apache-2.0 License.

import logging
from argparse import ArgumentParser
from pathlib import Path
from typing import List
import sys
import touca
from touca.cli._common import Operation
from touca._runner import run, _Workflow, Workflow

logger = logging.getLogger("touca.cli.check")


class Check(Operation):
    name = "check"
    help = "Submit the test output generated by other applications to the Touca Server"

    @classmethod
    def parser(self, parser: ArgumentParser):
        parser.add_argument(
            "src",
            help=f"path to file or directory to submit",
            nargs=1 if sys.stdin.isatty() else "?",
        )

    def __init__(self, options: dict):
        self.__options = options

    def _submit_stdin(self):
        content = sys.stdin.read()

        def _submit(testcase: str):
            touca.check("output", content)
            return

        testcase = "some-testcase"
        Workflow._workflows = [_Workflow(_submit, "example-suite", [testcase])]
        run(team="tutorial-232782")

        return False

    def _submit_file(self, file: Path):
        return False

    def _submit_files(self, files: List[Path]):
        return False

    def run(self) -> bool:
        if not sys.stdin.isatty():
            return self._submit_stdin()
        src = Path(self.__options.get("src")[0])
        if src.is_file():
            return self._submit_file(src)
        if src.is_dir():
            files = [file for file in src.glob("*") if file.is_file()]
            return self._submit_files(files)
        logger.error("specified path is neither a directory nor a file")
        return False
