version: "3"
services:
  touca_touca:
    user: "${UID_GID}"
    image: touca/touca:1.9.0
    environment:
      ENV_FILE: prod
      AUTH_JWT_SECRET: <SECRET>
      AUTH_COOKIE_SECRET: <SECRET>
      LOG_LEVEL: silly
      MINIO_USER: toucauser
      MINIO_PASS: toucapass
      MONGO_USER: toucauser
      MONGO_PASS: toucapass
      EXPRESS_ROOT: ""
      SAMPLES_ENABLED: "false"
      WEBAPP_ROOT: http://localhost
    depends_on:
      - touca_minio
      - touca_mongo
      - touca_redis
    ports:
      - 8080:8080
    restart: always

  touca_redis:
    user: "${UID_GID}"
    image: redis:6-alpine
    volumes:
      - ./data/redis:/data
    ports:
      - 6379:6379
    restart: always

  touca_minio:
    user: "${UID_GID}"
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    environment:
      MINIO_ROOT_USER: toucauser
      MINIO_ROOT_PASSWORD: toucapass
    volumes:
      - ./data/minio:/data
    ports:
      - 9000:9000
    command: server /data
    restart: always

  touca_mongo:
    user: "${UID_GID}"
    image: mongo:5
    environment:
      MONGO_INITDB_ROOT_USERNAME: toucauser
      MONGO_INITDB_ROOT_PASSWORD: toucapass
    volumes:
      - ./data/mongo:/data/db
      - ./ops/mongo/mongod.conf:/etc/mongod.conf
      - ./ops/mongo/entrypoint/:/docker-entrypoint-initdb.d/
    ports:
      - 27017:27017
    command: --config /etc/mongod.conf
    restart: always
