version: "3"
services:
  touca_api:
    image: 727591621296.dkr.ecr.us-east-2.amazonaws.com/touca-api:1.4.0
    environment:
      AUTH_COOKIE_SECRET: <SECRET>
      AUTH_GOOGLE_CLIENT_ID: <SECRET>
      AUTH_JWT_SECRET: <SECRET>
      AWS_REGION: <SECRET>
      AWS_ACCESS_KEY_ID: <SECRET>
      AWS_ACCESS_KEY_SECRET: <SECRET>
      AWS_LAMBDA_PDF_GENERATOR: <SECRET>
      DEPLOY_MODE: cloud_hosted
      DISCORD_CHANNEL: <SECRET>
      DISCORD_TOKEN: <SECRET>
      ENV_FILE: prod
      HUBSPOT_ACCESS_TOKEN: <SECRET>
      HUBSPOT_API_KEY: <SECRET>
      INTERCOM_ACCESS_TOKEN: <SECRET>
      INTERCOM_IDENTITY_SECRET: <SECRET>
      MAIL_TRANSPORT_HOST: <SECRET>
      MAIL_TRANSPORT_USER: <SECRET>
      MAIL_TRANSPORT_PASS: <SECRET>
      MAIL_TRANSPORT_PORT: 587
      MINIO_USER: toucauser
      MINIO_PASS: toucapass
      MIXPANEL_PROJECT_TOKEN: <SECRET>
      MONGO_USER: toucauser
      MONGO_PASS: toucapass
      WEBAPP_ROOT: https://app.touca.io

    volumes:
      - ./local/logs/api:/opt/local/logs/api
    depends_on:
      - touca_minio
      - touca_mongo
      - touca_redis
    # ports:
    #   - 8081:8081
    restart: always

  touca_app:
    image: 727591621296.dkr.ecr.us-east-2.amazonaws.com/touca-app:1.4.0
    depends_on:
      - touca_api
    ports:
      - 8090:80
    restart: always

  touca_cmp:
    image: 727591621296.dkr.ecr.us-east-2.amazonaws.com/touca-cmp:1.4.0
    environment:
      MINIO_USER: toucauser
      MINIO_PASS: toucapass
    volumes:
      - ./local/logs/cmp:/opt/local/logs/cmp
    depends_on:
      - touca_api
      - touca_minio
    restart: always

  touca_redis:
    image: redis:6-alpine
    volumes:
      - ./local/data/redis:/data
    # ports:
    #  - 6379:6379
    restart: always

  touca_minio:
    image: minio/minio:RELEASE.2021-03-17T02-33-02Z
    environment:
      MINIO_ROOT_USER: toucauser
      MINIO_ROOT_PASSWORD: toucapass
    volumes:
      - ./local/data/minio:/data
    # ports:
    #   - 9000:9000
    command: server /data
    restart: always

  touca_mongo:
    image: mongo:4-bionic
    environment:
      MONGO_INITDB_ROOT_USERNAME: toucauser
      MONGO_INITDB_ROOT_PASSWORD: toucapass
    volumes:
      - ./local/data/mongo:/data/db
      - ./ops/mongo/mongod.conf:/etc/mongod.conf
      - ./ops/mongo/entrypoint/:/docker-entrypoint-initdb.d/
    # ports:
    #   - 27017:27017
    command: --config /etc/mongod.conf
    restart: always

  touca_blog:
    image: ghost:4-alpine
    environment:
      url: https://blog.touca.io
      mail__transport: SMTP
      mail__options__host: <SECRET>
      mail__options__port: 465
      mail__options__service: SES
      mail__options__auth__user: <SECRET>
      mail__options__auth__pass: <SECRET>
    volumes:
      - ./local/data/ghost:/var/lib/ghost/content
    ports:
      - 2368:2368
    restart: always
