apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Release.Name }}-touca-redis
  name: {{ .Release.Name }}-touca-redis
  namespace: {{ .Release.Name }}-touca
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    app: {{ .Release.Name }}-touca-redis