# Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

name: touca-examples-javascript

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - ".github/workflows/build-js.yml"
      - "javascript/**"

jobs:
  test-native:
    name: unittest-native
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./javascript
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - name: get version number
        id: params
        run: |
          git fetch --prune --unshallow --tags
          echo "::set-output name=version::$(git describe --tags --abbrev=4)"
      - uses: actions/cache@v2
        with:
          path: |
            ${{ github.workspace }}/js/node_modules
            ${{ github.workspace }}/js/packages/**/node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - run: yarn install
      - run: yarn build
      - name: run example javascript application
        if: github.ref == 'refs/heads/main'
        env:
          TOUCA_API_KEY: ${{ secrets.TOUCA_API_KEY }}
          TOUCA_API_URL: https://api.touca.io/@/examples/javascript
          TOUCA_TEST_VERSION: ${{ steps.params.outputs.version }}
        run: |
          yarn --cwd=02_node_main_api test:touca
