#
# Copyright 2018-2020 Pejman Ghorbanzade. All rights reserved.
#

name: weasel-examples


on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - test

jobs:
  build-tutorial:
    name: build-tutorial
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cxx: [g++-9]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - name: cache conan
        uses: actions/cache@v2
        env:
          cache-name: cache-conan-packages
        with:
          path: ~/.conan
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ matrix.cxx }}-${{ hashFiles('**/build.sh') }}
      - name: install conan
        run: |
          pip install conan --no-cache-dir --upgrade
          conan profile new default --detect --force
          conan profile update settings.compiler.libcxx=libstdc++11 default
          conan remote add --force weasel-conan https://api.bintray.com/conan/getweasel/weasel-cpp
      - run: ./build.sh
      - name: run regression test
        env:
          WEASEL_API_KEY: ${{ secrets.WEASEL_API_KEY }}
        run: |
          mkdir -p ./local/results
          ./local/dist/bin/weasel_example_advanced -c ./advanced/config.json -r $(git describe --abbrev=4) --api-url https://getweasel.com/api/@/tutorial/advanced
