#
# Copyright 2018-2020 Pejman Ghorbanzade. All rights reserved.
#

name: touca-examples

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - test

jobs:
  build-tutorial:
    name: build-tutorial
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cxx: [g++-9]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-python@v1
      - run: ./build.sh
      - name: run regression test
        env:
          TOUCA_API_KEY: ${{ secrets.TOUCA_API_KEY }}
        run: |
          mkdir -p ./local/results
          ./local/dist/bin/touca_example_advanced -c ./advanced/config.json -r $(git describe --abbrev=4) --api-url https://api.touca.io/@/tutorial/advanced
