# Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

name: touca-examples-python

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - ".github/workflows/build-py.yml"
      - "python/**"

jobs:
  test-native:
    name: unittest-native
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./python
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: get version number
        id: params
        run: |
          git fetch --prune --unshallow --tags
          echo "::set-output name=version::$(git describe --tags --abbrev=4)"
      - name: run example python application
        env:
          TOUCA_API_KEY: ${{ secrets.TOUCA_API_KEY }}
          TOUCA_API_URL: https://api.touca.io/@/examples/python
        run: |
          pip install -r flowers/requirements.txt
          cd flowers && python regression_test.py --testcase-file testcases.txt --revision ${{ steps.params.outputs.version }}
