# Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

name: touca-examples-markdown

on:
  push:
    branches:
      - main
      - "feature/**"

jobs:
  check-markdown-links:
    name: check-markdown-links
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v2
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
