# Copyright 2021 Touca, Inc. Subject to Apache-2.0 License.

name: touca-examples-cpp

on:
  push:
    branches:
      - main
      - 'feature/**'
    paths:
      - ".github/workflows/build-cpp.yml"
      - "cpp/**"

jobs:
  test-native:
    name: unittest-native
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./cpp
    strategy:
      matrix:
        cxx: [g++-9]
    steps:
      - uses: actions/checkout@v2
      - name: get version number
        id: params
        run: |
          git fetch --prune --unshallow --tags
          echo "::set-output name=version::$(git describe --tags --abbrev=4)"
      - name: build cpp examples
        run: ./build.sh
      - name: run example cpp application
        env:
          TOUCA_API_KEY: ${{ secrets.TOUCA_API_KEY }}
        run: |
          mkdir -p ./local/results
          ./local/dist/bin/touca_example_advanced -c ./advanced/config.json --api-url https://api.touca.io/@/examples/cpp --revision ${{ steps.params.outputs.version }}
