# Copyright 2022 Touca, Inc. Subject to Apache-2.0 License.

name: touca-release-sdk-js

on:
  workflow_dispatch:

jobs:
  publish-npm:
    name: release-publish-npm
    runs-on: ubuntu-20.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./sdk/js
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: "https://registry.npmjs.org"
      - run: npm ci
      - run: npm run build:prod
      - name: build package distributable
        run: |
          rm packages/node/README.md
          cp LICENSE packages/node/LICENSE
          cp Changelog.md packages/node/Changelog.md
          cp README.md packages/node/README.md
          sed -i 's/\("main":\).*/\1 "dist\/index.js",/g' packages/node/package.json
          sed -i 's/\("types":\).*/\1 "dist\/index.d.ts",/g' packages/node/package.json
      - run: |
          cd packages/node && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
