# Copyright 2022 Touca, Inc. Subject to Apache-2.0 License.

name: touca-release-sdk-python

on:
  workflow_dispatch:

jobs:
  publish-pypi:
    name: release-publish-pypi
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./sdk/python
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Run image
        run: |
          pip install poetry=="1.2.2"
      - name: build and publish
        env:
          PYPI_USERNAME: __token__
          PYPI_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish -u PYPI_USERNAME -p PYPI_PASSWORD --build
