# Copyright 2023 Touca, Inc. Subject to Apache-2.0 License.

name: touca-release-sdk-python

on:
  workflow_dispatch:

jobs:
  publish-pypi:
    name: release-publish-pypi
    runs-on: ubuntu-22.04
    timeout-minutes: 5
    defaults:
      run:
        working-directory: ./sdk/python
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install poetry
        run: |
          python -m pip install --upgrade pip
          pip install poetry=="1.2.2"
      - name: install package
        run: poetry install
      - name: build package
        run: poetry build
      - name: publish package
        run: poetry publish
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN_FBS }}
