# Copyright 2022 Touca, Inc. Subject to Apache-2.0 License.

name: touca-self-host-install

on:
  workflow_dispatch:
  push:
    branches:
      - "feature/self-host"

jobs:
  touca-self-host-install:
    name: touca-self-host-install
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: run integration tests
        run: |
          rm -rf {data,logs}
          mkdir -p logs/{backend,cmp} data/{minio,mongo,redis}
          docker-compose -f ops/docker-compose.test.yml --project-directory . -p touca up -d
          sleep 15
          docker-compose -f ops/docker-compose.test.yml --project-directory . -p touca logs touca_api
          cd api/e2e
          pip install -r requirements.txt
          python .
          docker-compose -f ops/docker-compose.test.yml --project-directory . -p touca logs touca_api
      - if: always()
        run: |
          docker-compose -f ops/docker-compose.test.yml --project-directory . -p touca down
