# Copyright 2023 Touca, Inc. Subject to Apache-2.0 License.

name: touca-self-host-install

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
    paths:
      - "api/e2e"
      - "ops/docker-compose.test.yml"
      - ".github/workflows/self-host-install.yml"

jobs:
  touca-self-host-install:
    name: touca-self-host-install
    runs-on: ubuntu-latest
    timeout-minutes: 15
    defaults:
      run:
        working-directory: ./api/e2e
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
          cache: "pip"
      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry=="1.2.2"
          poetry install
      - name: setup containers
        run: |
          poetry run touca server install --install-dir ~/.touca/server --test
      - name: run integration tests
        run: poetry run reset
      - name: show container logs
        if: failure()
        run: poetry run touca server logs
      - name: shutdown containers
        if: always()
        run: poetry run touca server uninstall
