# Copyright 2022 Touca, Inc. Subject to Apache-2.0 License.

name: touca-self-host-install

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"
  push:
    paths:
      - "api/e2e"
      - "ops/docker-compose.test.yml"
      - ".github/workflows/self-host-install.yml"

jobs:
  touca-self-host-install:
    name: touca-self-host-install
    runs-on: ubuntu-20.04
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
          cache: "pip"
      - name: setup containers
        run: |
          mkdir -p logs/api data/{minio,mongo,redis}
          docker-compose -f ops/docker-compose.test.yml --project-directory . -p touca up -d
      - name: run integration tests
        run: |
          pip install -r api/e2e/requirements.txt
          python api/e2e
      - name: show container logs
        if: failure()
        run: |
          docker-compose -f ops/docker-compose.test.yml --project-directory . -p touca logs touca_touca
      - name: shutdown containers
        if: always()
        run: |
          docker-compose -f ops/docker-compose.test.yml --project-directory . -p touca down
