apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: touca-app
  name: touca-app
  namespace: touca
spec:
  replicas: 1
  selector:
    matchLabels:
      app: touca-app
  template:
    metadata:
      labels:
        app: touca-app
    spec:
      containers:
        - image: touca/touca:1.9.0
          name: touca-app
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: ENV_FILE
              value: prod
            - name: WEBAPP_ROOT
              value: "http://touca-app"
            - name: MINIO_HOST
              value: touca-minio
            - name: MONGO_HOST
              value: touca-mongo
            - name: REDIS_HOST
              value: touca-redis
            - name: MINIO_USER
              value: toucauser
            - name: MINIO_PASS
              value: toucapass
            - name: MONGO_USER
              value: toucauser
            - name: MONGO_PASS
              value: toucapass
