apiVersion: v1
kind: Service
metadata:
  labels:
    app: touca-app
  name: touca-app
  namespace: touca
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: touca-app