apiVersion: v1
kind: Service
metadata:
  labels:
    app: touca-api
  name: touca-api
  namespace: touca
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: touca-api
