apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: touca-cert  #name of this object
  namespace: touca #same namespace as 
spec:
  dnsNames:
    - k8s.trytouca.com
  secretName: touca-tls-cert
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
